# Generated by Django 5.2.7 on 2025-11-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('partido', models.CharField(max_length=100)),
                ('biografia', models.TextField()),
                ('experiencia', models.TextField()),
                ('visitas', models.IntegerField(default=0)),
                ('foto_url', models.URLField()),
            ],
        ),
    ]
