# Generated by Django 5.2.7 on 2025-11-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='foto_url',
        ),
        migrations.AddField(
            model_name='candidato',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='candidatos/'),
        ),
    ]
