# Generated by Django 5.2.7 on 2025-11-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0002_remove_candidato_foto_url_candidato_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='experiencia',
            field=models.IntegerField(default=0),
        ),
    ]
