# Generated by Django 5.2.7 on 2025-11-03 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0003_alter_candidato_experiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='dni',
            field=models.CharField(default='00000000', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidato',
            name='estado',
            field=models.CharField(default='Activo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidato',
            name='nacimiento',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidato',
            name='region',
            field=models.CharField(default='Lima', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('expediente', models.CharField(max_length=100)),
                ('delito', models.CharField(max_length=100)),
                ('fecha_denuncia', models.DateField()),
                ('estado', models.CharField(max_length=100)),
                ('fuente_url', models.URLField()),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias', to='candidatos.candidato')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.TextField()),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cargos', to='candidatos.candidato')),
            ],
        ),
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('prioridad', models.CharField(max_length=50)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas', to='candidatos.candidato')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='candidatos.candidato')),
            ],
        ),
    ]
