# Generated by Django 5.2.7 on 2025-11-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0004_candidato_dni_candidato_estado_candidato_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='dni',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='estado',
            field=models.CharField(default='Activo', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='experiencia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='region',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='visitas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
