# Generated by Django 5.2.7 on 2025-11-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0005_alter_candidato_dni_alter_candidato_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='fuente_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialcargo',
            name='fuente_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='fuente_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fuente_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
