# Generated by Django 5.2.7 on 2025-11-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0006_candidato_fuente_url_historialcargo_fuente_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='profesion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
