# Generated by Django 5.2.7 on 2025-11-07 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0007_candidato_profesion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='experiencia',
        ),
    ]
