# Generated by Django 5.2.7 on 2025-11-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0008_remove_candidato_experiencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='foto',
        ),
        migrations.AddField(
            model_name='candidato',
            name='foto_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
