# Generated by Django 5.2.7 on 2025-11-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0010_alter_candidato_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcargo',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
