# Generated by Django 5.2.7 on 2025-11-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0011_alter_historialcargo_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuesta',
            name='prioridad',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Media', max_length=50),
        ),
    ]
