# Generated by Django 5.2.7 on 2025-11-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0012_alter_propuesta_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('Sin iniciar', 'Sin iniciar'), ('En ejecución', 'En ejecución'), ('Finalizado', 'Finalizado')], default='Sin iniciar', max_length=50),
        ),
    ]
